### ISSUE TITLE
Error while npm install

### ISSUE THREAD

**Issue by pepsi7959** [digital-solution-consulting/survey#101]
```bash
root@Linux_WEB1:/var/www/stag/survey/backend# npm install 

> hiredis@0.5.0 install /var/www/stag/survey/backend/node_modules/hiredis
> node-gyp rebuild

gyp WARN EACCES user "scdadmin" does not have permission to access the dev dir "/root/.cache/node-gyp/12.10.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/var/www/stag/survey/backend/node_modules/hiredis/.node-gyp"
make: Entering directory '/var/www/stag/survey/backend/node_modules/hiredis/build'
  CC(target) Release/obj.target/hiredis-c/deps/hiredis/sds.o
  CC(target) Release/obj.target/hiredis-c/deps/hiredis/read.o
  AR(target) Release/obj.target/deps/hiredis-c.a
  COPY Release/hiredis-c.a
  CXX(target) Release/obj.target/hiredis/src/hiredis.o
  CXX(target) Release/obj.target/hiredis/src/reader.o
../src/reader.cc: In function 'void* tryParentize(const redisReadTask*, const v8::Local<v8::Value>&)':
../src/reader.cc:21:32: warning: 'bool v8::Object::Set(uint32_t, v8::Local<v8::Value>)' is deprecated: Use maybe version [-Wdeprecated-declarations]
         larray->Set(task->idx,v);
                                ^
In file included from /var/www/stag/survey/backend/node_modules/hiredis/.node-gyp/12.10.0/include/node/v8-internal.h:14:0,
                 from /var/www/stag/survey/backend/node_modules/hiredis/.node-gyp/12.10.0/include/node/v8.h:25,
                 from /var/www/stag/survey/backend/node_modules/hiredis/.node-gyp/12.10.0/include/node/node.h:63,
                 from ../../nan/nan.h:54,
                 from ../src/reader.h:1,
                 from ../src/reader.cc:3:
/var/www/stag/survey/backend/node_modules/hiredis/.node-gyp/12.10.0/include/node/v8.h:3381:22: note: declared here
                 bool Set(uint32_t index, Local<Value> value));
                      ^
/var/www/stag/survey/backend/node_modules/hiredis/.node-gyp/12.10.0/include/node/v8config.h:311:3: note: in definition of macro 'V8_DEPRECATED'
   declarator __attribute__((deprecated(message)))
   ^
../src/reader.cc: In function 'void* createString(const redisReadTask*, char*, size_t)':
../src/reader.cc:55:42: error: no matching function for call to 'v8::Value::ToString()'
         v = Exception::Error(v->ToString());
                                          ^
In file included from /var/www/stag/survey/backend/node_modules/hiredis/.node-gyp/12.10.0/include/node/node.h:63:0,
                 from ../../nan/nan.h:54,
                 from ../src/reader.h:1,
                 from ../src/reader.cc:3:
/var/www/stag/survey/backend/node_modules/hiredis/.node-gyp/12.10.0/include/node/v8.h:2541:44: note: candidate: v8::MaybeLocal<v8::String> v8::Value::ToString(v8::Local<v8::Context>) const
   V8_WARN_UNUSED_RESULT MaybeLocal<String> ToString(
                                            ^
/var/www/stag/survey/backend/node_modules/hiredis/.node-gyp/12.10.0/include/node/v8.h:2541:44: note:   candidate expects 1 argument, 0 provided
In file included from /var/www/stag/survey/backend/node_modules/hiredis/.node-gyp/12.10.0/include/node/v8-internal.h:14:0,
                 from /var/www/stag/survey/backend/node_modules/hiredis/.node-gyp/12.10.0/include/node/v8.h:25,
                 from /var/www/stag/survey/backend/node_modules/hiredis/.node-gyp/12.10.0/include/node/node.h:63,
                 from ../../nan/nan.h:54,
                 from ../src/reader.h:1,
                 from ../src/reader.cc:3:
/var/www/stag/survey/backend/node_modules/hiredis/.node-gyp/12.10.0/include/node/v8.h:2557:31: note: candidate: v8::Local<v8::String> v8::Value::ToString(v8::Isolate*) const
                 Local<String> ToString(Isolate* isolate) const);
                               ^
/var/www/stag/survey/backend/node_modules/hiredis/.node-gyp/12.10.0/include/node/v8config.h:311:3: note: in definition of macro 'V8_DEPRECATED'
   declarator __attribute__((deprecated(message)))
   ^
/var/www/stag/survey/backend/node_modules/hiredis/.node-gyp/12.10.0/include/node/v8.h:2557:31: note:   candidate expects 1 argument, 0 provided
                 Local<String> ToString(Isolate* isolate) const);
                               ^
/var/www/stag/survey/backend/node_modules/hiredis/.node-gyp/12.10.0/include/node/v8config.h:311:3: note: in definition of macro 'V8_DEPRECATED'
   declarator __attribute__((deprecated(message)))
   ^
hiredis.target.mk:121: recipe for target 'Release/obj.target/hiredis/src/reader.o' failed
make: *** [Release/obj.target/hiredis/src/reader.o] Error 1
make: Leaving directory '/var/www/stag/survey/backend/node_modules/hiredis/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:196:23)
gyp ERR! stack     at ChildProcess.emit (events.js:209:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Linux 4.4.0-62-generic
gyp ERR! command "/usr/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /var/www/stag/survey/backend/node_modules/hiredis
gyp ERR! node -v v12.10.0
gyp ERR! node-gyp -v v5.0.3
gyp ERR! not ok 
npm WARN ajv-keywords@3.4.0 requires a peer of ajv@^6.9.1 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! hiredis@0.5.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the hiredis@0.5.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-10-05T04_40_05_282Z-debug.log
```

**Comment by pepsi7959** [comment]
npm uninstall hiredis
